# .github/FUNDING.yml

# Patreon
patreon: simar10   # your Patreon username

# Buy Me a Coffee
ko_fi: simar10     # your Buy Me a Coffee username

# Custom links
custom: 
  - "https://www.patreon.com/c/simar10"
  - "https://buymeacoffee.com/simar10"
